### ISSUE TITLE
Integration Example is missing critical setup information

### ISSUE THREAD

**Issue by connormcwood** [ematipico/terraform-nextjs-plugin#117]
As the title suggests. 

When building the terraform files using the build.js file created many resources are created that if ran are not created. As a result of that when creating those terraform resources to match up with the desired routes it is not clear what should to where.

For example `data.archive_file.packLambda-index` resource is required but it is not clear what file this resource should point to. Unfortunately this repository seems to be missing a lot of initial set up information and as a result of that it will limit adoption. 

I can see that creating the main resources and letting the tf.json file fill in the property values should allow for the creation of the resources. However, there seems to be an issue with the suffix .html that prevents various resources from being deployed. (Using TF 0.11)

`Error asking for user input: Error parsing address 'aws_api_gateway_resource.CustomKey-index.html': Unexpected value for InstanceType field: "html"`

**Comment by connormcwood** [comment]
Issue due to mismatch between defined routes and correlated js page file.

**Comment by ematipico** [comment]
Hi @connormcwood, thank you for you feedback!

The initial idea and setup of this project was to create the resources from the **JavaScript** files created from Next.js. I haven't thought that it was a case to publish an `.html` file as lambda. I think it should not be the case.

If you feel there are some missing information about how to use the tool, please let me know what I should make more clear! Thank you!

**Comment by connormcwood** [comment]
> Hi @connormcwood, thank you for you feedback!
> 
> The initial idea and setup of this project was to create the resources from the **JavaScript** files created from Next.js. I haven't thought that it was a case to publish an `.html` file as lambda. I think it should not be the case.
> 
> If you feel there are some missing information about how to use the tool, please let me know what I should make more clear! Thank you!

Thanks for the reply. The issue was due to a mismatch between the defined routes and their correlated javascript file in the pages folder.
